name: ci
on:
  - push

jobs:
  perl:
    container:
      image: perl:sha256:5cbbc12a9e1719e7cabb5fdd10245ac6ddf93909cf89c2ae34e8ea483724c46e
    steps:
      - uses: actions/checkout@v1
      - run: |
          cpanm -nq --dev Carmel
          carmel install
          
          